[python]
prompt     = '>>> '
lexer      = "python"
executable = "/usr/bin/python -q"
multiline  = []
  [python.files]
  history = ".python_history"
  init    = ""

[lua]
prompt     = '> '
lexer      = "lua"
executable = "/usr/bin/lua"
multiline  = []
  [lua.files]
  history = ".lua_history"
  init    = ""

[chicken]
prompt     = '#;\d+> '
lexer      = "scheme"
executable = "/usr/bin/chicken-csi"
multiline  = []
  [chicken.files]
  history = ".chicken-csi_history"
  init    = ""

[ruby]
prompt     = 'irb\\(main\\):(\d+):\d+> '
lexer      = "ruby"
executable = "/usr/bin/irb"
multiline  = []
  [ruby.files]
  history = ".irb_history"
  init    = ""

[factor]
prompt     = 'IN: (\w+) '
lexer      = "factor"
executable = "/usr/bin/factor-vm -run=readline-listener"
multiline  = []
  [factor.files]
  history = ".factor_history"
  init    = ""

[haskell]
prompt     = '(\w+)> '
lexer      = "haskell"
executable = "/usr/bin/ghci"
multiline  = [ ':{', ':}' ]
  [haskell.files]
  history = "~/.haskell_history"
  init    = "~/.ghci"

[javascript]
prompt     = '> '
lexer      = "javascript"
executable = "/usr/bin/node"
multiline  = []
  [javascript.fies]
  history = "~/.node_repl_history"
  init    = ""

